<?php

session_start();
include '../../pwjafflite_config.php';
include '../lang/'.$language;

if(!aff_admin_check_security())
{
    aff_redirect('index.php');
    exit();
}
	
?>
<html>
<head>
<title>Invoice Generated By Sistem Affiliate Lite Version</title>
<meta http-equiv=Content-Type content=text/html; charset=iso-8859-1>
</head>
<style type="text/css">
<!--
.bordersolid1 {
	border: 2px solid #333333;
	padding: 15px;
	text-align: left;
	font-family: verdana;
	font-size: 12px;
}
.footer {
	text-align:center;
	font-family:verdana;
	font-size:10px;
	color:#000000;
	padding-left: 20px;
	padding-right: 20px;
}
h1 {
	font-size: 24px;
	font-weight: bold;
	text-align: center;
}
h2 {
	font-size: 16px;
	font-weight: bold;
	text-align: center;
}
h3 {
	font-size: 14px;
	font-weight: bold;
	text-align: left;
}

-->
</style>
<script type="text/javascript">
function printpage()
  {
  window.print()
  }
</script>
</head>
<body><div align="center">
<table bgcolor="#FFFFFF" width="500" class="bordersolid1">
  <tr>
    <td><h1>Commission Invoice<br /><?=$namaproduk?></h1></td>
  </tr>
  <tr>
	<td><h2> <?=AFF_AA_INVOICEINFO?> - <?=$_REQUEST['agen']?></h2></td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC" valign="middle"><h3> <?=AFF_AA_INVOICEAGEN?> (ID:  <?=$_REQUEST['agen']?>)</h3></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>	
    <td valign="top">
    <?php
	$result = mysql_query("SELECT * FROM affiliates WHERE refid = '".$_REQUEST['agen']."'", $database_connection) or die ('Database CONNECT Error');
	if (mysql_num_rows($result))
	{
		while ($qry = mysql_fetch_array($result))
		{
			// Data Needed
			$paymentprocessor = $qry['processor'];
			$accountnumber = $qry['account'];
			$accountholder = $qry['payto'];
			
			print $qry['title'];
			print ' ';
			print $qry['firstname'];
			print ' ';
			print $qry['lastname'];
			print ",<br />";
			print $qry['street'];
			print ', ';
			print $qry['town'];
			print ',<br />';
			print $qry['postcode'];
			print ' ';	  
			print $qry['county'];
			print ', ';
			print $qry['country'];
			print ".<br /><br />";
			print 'Tel: ';
			print $qry['phone'];
			print '<br />';	  
			print 'E-mail: ';
			print $qry['email'];
			print '<br>';
			print 'Website: ';
			print $qry['website'];
		}
    }
	?>
	</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC" valign="middle"><h3><?=AFF_AA_INVOICEPAYINFO?></h3></td>
  </tr>
    <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><?=AFF_AA_INVOICEPAYINFOSUM?>: <u><?=$currency?>
      <?php
      
	  $set = mysql_query("SELECT SUM(payment) AS total FROM sales WHERE refid = '".$_REQUEST['agen']."' and statuspelanggan = '".AFF_AS_STATUSVERIFIED."'", $database_connection) or die ('Database CONNECT Error');
		
    $row = mysql_fetch_array($set);
    print $row['total'];
	print '</u><br /><br />'.AFF_AA_INVOICEPAYINFODATE.': <u>';
	print (date ('Y-m-d')); 
    print '</u>';
	?>
	</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC" valign="middle"><h3><?=AFF_AA_INVOICEPAY?></h3></td>
  </tr>
    <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
    Payment Processor: <?=$paymentprocessor?>
    <br /><br />
    Account Number: <?=$accountnumber?>
	<br /><br />
    Account Holder: <?=$accountholder?>
	</td>
   <td>&nbsp;</td>
  </tr>
  <tr>
    <td><hr /></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><?=AFF_AA_INVOICEDONE?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
	<td><?=AFF_AA_INVOICESIGNATURE?>
	<br /><h3><?=$admininfo?></h3>
	<br /><?=$namaproduk?>
	<br />http://<?=$domain?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><input type="button" value="Print this page" onclick="printpage()" /></td>
  </tr>
  <tr>
    <td><hr /></td>
  </tr>
  <tr>
    <td class="footer">Affiliate Programme By <a href="http://<?=$domain?>" target="_blank"><?=$namaproduk?></a> <?=$tahunoperasi?>.<br /><br />Affiliate Script Powered By <a href="http://www.sistemaffiliate.com/?aff_id=<?=$idaffiliatePIS?>" target="_blank">Sistem Affiliate Lite</a>.</td></tr></table>
    </div>
</body>

</html>